version: '3.8'

services:
  backend-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ns_backend_go
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    networks:
      - ns_network

networks:
  ns_network:
    driver: bridge
